/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package car_rental_management_system;

import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import Classes.Car;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author Administrator
 */
public class car_image extends javax.swing.JFrame {

    /**
     * Creates new form car_image
     */
    Classes.Car car = new Classes.Car(0, null, null, null, 0, null, null,0, null, null, null, null, null, null, null, null, null, null);
    ArrayList<Car> carlist=car.carlist();
     int index=0;
    public car_image() {
        initComponents();
        this.setLocationRelativeTo(null);
        populateJtablewithcar();
        
        
    }
    public void display_image(int width,int height, String image, JLabel l1)
    {
       ImageIcon imageicon=new  ImageIcon((image));
       Image imag=imageicon.getImage().getScaledInstance(width, height, Image.SCALE_SMOOTH);
       l1.setIcon(new ImageIcon(imag));
       
    } 
      public String set_image()
          {
              JFileChooser file=new JFileChooser();
              file.setDialogTitle("Select the picture");
              file.setCurrentDirectory(new File("c:\\image"));
              FileNameExtensionFilter filter=new FileNameExtensionFilter("image","png","jpg");
              file.addChoosableFileFilter(filter);
              int state =file.showSaveDialog(null);
              String path="";
              if(state == JFileChooser.APPROVE_OPTION)
              {
                  path=file.getSelectedFile().getAbsolutePath();
              }
                                 
              return path;
          }
       public void populateJtablewithcar()
       {
              String[] columnname={"id","Model","class"};
              Object[][] rows =new Object[carlist.size()][columnname.length];
              for(int i=0;i<carlist.size();i++)
              {
                  rows[i][0]=carlist.get(i).getId();
                  rows[i][1]=carlist.get(i).getModel();
                  rows[i][2]=carlist.get(i).getClasss();
                 
              }
              DefaultTableModel model=new DefaultTableModel(rows,columnname);
              jtable_select_car.setModel(model);
          }
           public void populateJtablewithcar_image(int car_id)
       {
            ArrayList<Car.CarImage> car_image_list=car.carimagelist(car_id);
              String[] columnname={" Image Id"};
              Object[][] rows =new Object[car_image_list.size()][columnname.length];
              for(int i=0;i<car_image_list.size();i++)
              {
                  rows[i][0]=car_image_list.get(i);
                 
              }
              DefaultTableModel model=new DefaultTableModel(rows,columnname);
              jtable_car_image.setModel(model);
          }
           
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        product_logo = new javax.swing.JLabel();
        product_logo1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtable_car_image = new javax.swing.JTable();
        jLabel_logo = new javax.swing.JLabel();
        jButton_image_add = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtable_select_car = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton_select_image = new javax.swing.JButton();
        jButton_remove_pic = new javax.swing.JButton();
        jButton_image_slide1 = new javax.swing.JButton();
        jLable_imagePath = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(0, 204, 255));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 11, true));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 204, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 255, 255)));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Car Image");
        jLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 7, true));

        product_logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        product_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-car-fire-68.png"))); // NOI18N

        product_logo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        product_logo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-car-fire-68.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(509, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(406, 406, 406)
                .addComponent(product_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(38, 38, 38)
                    .addComponent(product_logo1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1119, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(product_logo, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(product_logo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 11, 1270, -1));

        jtable_car_image.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jtable_car_image.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jtable_car_image.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jtable_car_image.setGridColor(new java.awt.Color(255, 255, 255));
        jtable_car_image.setSelectionBackground(new java.awt.Color(0, 153, 255));
        jtable_car_image.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jtable_car_image.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtable_car_imageMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtable_car_image);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 140, 490, 380));

        jLabel_logo.setBackground(new java.awt.Color(102, 102, 102));
        jLabel_logo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jLabel_logo.setOpaque(true);
        jPanel3.add(jLabel_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, 270, 180));

        jButton_image_add.setBackground(new java.awt.Color(255, 102, 0));
        jButton_image_add.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_image_add.setForeground(new java.awt.Color(255, 255, 255));
        jButton_image_add.setText("Add Image");
        jButton_image_add.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        jButton_image_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_image_addActionPerformed(evt);
            }
        });
        jPanel3.add(jButton_image_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 490, 220, 40));

        jtable_select_car.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jtable_select_car.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jtable_select_car.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jtable_select_car.setGridColor(new java.awt.Color(255, 255, 255));
        jtable_select_car.setRowHeight(40);
        jtable_select_car.setSelectionBackground(new java.awt.Color(0, 153, 255));
        jtable_select_car.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jtable_select_car.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtable_select_carMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtable_select_car);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 470, 380));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Select Car ");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 255), 4, true));
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 250, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Select Car image");
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 255), 4, true));
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 100, 250, 40));

        jButton_select_image.setBackground(new java.awt.Color(255, 102, 0));
        jButton_select_image.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_select_image.setForeground(new java.awt.Color(255, 255, 255));
        jButton_select_image.setText("Select image");
        jButton_select_image.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        jButton_select_image.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_select_imageActionPerformed(evt);
            }
        });
        jPanel3.add(jButton_select_image, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 340, 220, 40));

        jButton_remove_pic.setBackground(new java.awt.Color(255, 0, 0));
        jButton_remove_pic.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_remove_pic.setForeground(new java.awt.Color(255, 255, 255));
        jButton_remove_pic.setText("Remove");
        jButton_remove_pic.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        jButton_remove_pic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_remove_picActionPerformed(evt);
            }
        });
        jPanel3.add(jButton_remove_pic, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 390, 220, 40));

        jButton_image_slide1.setBackground(new java.awt.Color(255, 102, 0));
        jButton_image_slide1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_image_slide1.setForeground(new java.awt.Color(255, 255, 255));
        jButton_image_slide1.setText("Image Slide");
        jButton_image_slide1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        jButton_image_slide1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_image_slide1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton_image_slide1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 440, 220, 40));

        jLable_imagePath.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLable_imagePath.setText("######");
        jLable_imagePath.setOpaque(true);
        jPanel3.add(jLable_imagePath, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, 220, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1295, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtable_car_imageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtable_car_imageMouseClicked

    }//GEN-LAST:event_jtable_car_imageMouseClicked

    private void jButton_image_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_image_addActionPerformed
         
        try {
            int index=jtable_select_car.getSelectedRow();
            int car_id=Integer.valueOf(jtable_select_car.getValueAt(index, 0).toString());
            byte[] image=Files.readAllBytes(Paths.get(jLable_imagePath.getText()));
           car.addcar_image(car_id,image);
        } catch (Exception ex) {
           Logger.getLogger(Car .class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_image_addActionPerformed

    private void jtable_select_carMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtable_select_carMouseClicked
        int index=jtable_select_car.getSelectedRow();
        int id =Integer.valueOf(jtable_select_car.getValueAt(index, 0).toString());
        JOptionPane.showMessageDialog(this,"select the id number:"+id);
        populateJtablewithcar_image(id);
        
           
    }//GEN-LAST:event_jtable_select_carMouseClicked

    private void jButton_select_imageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_select_imageActionPerformed
           String image= set_image();
      display_image(jLabel_logo.getWidth(),jLabel_logo.getHeight(),image,jLabel_logo);
      jLable_imagePath.setText(image);
    }//GEN-LAST:event_jButton_select_imageActionPerformed

    private void jButton_remove_picActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_remove_picActionPerformed
int index=jtable_select_car.getSelectedRow();
        int id=Integer.valueOf(jtable_select_car.getValueAt(index, 0).toString());
        int confirm=JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this CAR?", "confirm",JOptionPane.YES_NO_OPTION);
        if(confirm==JOptionPane.YES_NO_OPTION)
        {    
        car.delete_car(id);
        }
       
    }//GEN-LAST:event_jButton_remove_picActionPerformed

    private void jButton_image_slide1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_image_slide1ActionPerformed

    }//GEN-LAST:event_jButton_image_slide1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(car_image.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(car_image.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(car_image.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(car_image.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new car_image().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_image_add;
    private javax.swing.JButton jButton_image_slide1;
    private javax.swing.JButton jButton_remove_pic;
    private javax.swing.JButton jButton_select_image;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel_logo;
    private javax.swing.JLabel jLable_imagePath;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jtable_car_image;
    private javax.swing.JTable jtable_select_car;
    private javax.swing.JLabel product_logo;
    private javax.swing.JLabel product_logo1;
    // End of variables declaration//GEN-END:variables
}
