/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package car_rental_management_system;

import Classes.Brand;
import Classes.Car;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class Car_form extends javax.swing.JFrame {

    /**
     * Creates new form Car
     */
    Classes.Car car = new Classes.Car(0, null, null, null, 0, null, null, 0, null, null, null, null, null, null, null, null, null, null);
    Classes.Brand brand = new Classes.Brand(0, null, null);
    HashMap<String,Integer> map = brand.brandhashmap();

    public Car_form() {
        initComponents();
        this.setLocationRelativeTo(null);
        feauture_comboboxBrand();
    }
    
    

    public void feauture_comboboxBrand() {
        
        
        for (String s : map.keySet()) {
            jComboBox_brand.addItem(s);
        }

    }

    public boolean verify() {
        String model = jTextField_model.getText();
        String classs = jTextField_model.getText();
       if(!model.trim().equals("")&&!classs.trim().equals(""))
       {
           return true;
       }
       else
       {
           JOptionPane.showMessageDialog(this,"Enter the valid model and Classs","invalid Information",2);
           
       }
        return false;
      

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jCheckBox_Gearbox_auto = new javax.swing.JCheckBox();
        jCheckBoxGearbox_manual = new javax.swing.JCheckBox();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jTextField_price = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField_class = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        product_logo = new javax.swing.JLabel();
        product_logo1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_Reset = new javax.swing.JButton();
        jButton_add_car = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jCheckBox_feature_air_cond = new javax.swing.JCheckBox();
        jCheckBox_feature_air_bags = new javax.swing.JCheckBox();
        jCheckBox_feature_sunroof = new javax.swing.JCheckBox();
        jCheckBox_feauture_heat = new javax.swing.JCheckBox();
        jCheckBox_blue = new javax.swing.JCheckBox();
        jCheckBox_electric = new javax.swing.JCheckBox();
        jCheckBox_navigation = new javax.swing.JCheckBox();
        jCheckBox_feature_gps = new javax.swing.JCheckBox();
        jCheckBox_feauture_automatic = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        jTextField_model = new javax.swing.JTextField();
        jComboBox_brand = new javax.swing.JComboBox<>();
        jComboBox_fuel = new javax.swing.JComboBox<>();
        jComboBox_color = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jSpinner_search_id = new javax.swing.JSpinner();
        btn_add_car_image = new javax.swing.JButton();
        jRadioButton_autmatic = new javax.swing.JRadioButton();
        jRadioButton_manual = new javax.swing.JRadioButton();
        btn_brand_list1 = new javax.swing.JButton();
        int max=1000;
        int min=10;
        int Step=1;
        int i=10;
        SpinnerModel spinner_model=new SpinnerNumberModel(i,min,max,Step);
        jSpinner_price =new javax.swing.JSpinner();
        jSpinner_price = new javax.swing.JSpinner(spinner_model);
        jComboBox_classs = new javax.swing.JComboBox<>();
        btn_delete = new javax.swing.JButton();
        jButton2_update = new javax.swing.JButton();
        btn_car_list = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        int max_2=10;
        int min_2=2;
        int Step_2=1;
        int i_2=2;
        SpinnerModel spinner_model_2=new SpinnerNumberModel(i_2,min_2,max_2,Step_2);
        jSpinner_passenger1 = new javax.swing.JSpinner(spinner_model_2);
        jButton_search = new javax.swing.JButton();

        jLabel5.setText("jLabel5");

        jCheckBox_Gearbox_auto.setBackground(new java.awt.Color(0, 153, 153));
        jCheckBox_Gearbox_auto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jCheckBox_Gearbox_auto.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox_Gearbox_auto.setText("Automatic");
        jCheckBox_Gearbox_auto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        jCheckBoxGearbox_manual.setBackground(new java.awt.Color(0, 153, 153));
        jCheckBoxGearbox_manual.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jCheckBoxGearbox_manual.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxGearbox_manual.setText("Manual");

        jTextField_price.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextField_price.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTextField_class.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextField_class.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        jLabel1.setText("jLabel1");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 102, 0));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 11, true));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 255, 255)));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Cars");
        jLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 7, true));

        product_logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        product_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-car-fire-68.png"))); // NOI18N

        product_logo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        product_logo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-car-fire-68.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(320, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(205, 205, 205)
                .addComponent(product_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(38, 38, 38)
                    .addComponent(product_logo1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(729, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(product_logo, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(product_logo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 11, 880, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Brand:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, 43));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Model:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 80, 38));

        btn_Reset.setBackground(new java.awt.Color(255, 0, 0));
        btn_Reset.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_Reset.setForeground(new java.awt.Color(255, 255, 255));
        btn_Reset.setText("Reset");
        btn_Reset.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btn_Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ResetActionPerformed(evt);
            }
        });
        jPanel3.add(btn_Reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 550, 136, 40));

        jButton_add_car.setBackground(new java.awt.Color(255, 153, 51));
        jButton_add_car.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_add_car.setForeground(new java.awt.Color(255, 255, 255));
        jButton_add_car.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-add-37.png"))); // NOI18N
        jButton_add_car.setText("Add");
        jButton_add_car.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jButton_add_car.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_add_carActionPerformed(evt);
            }
        });
        jPanel3.add(jButton_add_car, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 128, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Fuel:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 80, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Passenger:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 100, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Color:");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Class:");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 50, 40));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Price/day:");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, 90, 30));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        jCheckBox_feature_air_cond.setText("Air Conditioning");
        jCheckBox_feature_air_cond.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jCheckBox_feature_air_bags.setText("Airbags");

        jCheckBox_feature_sunroof.setText("Sunroof");
        jCheckBox_feature_sunroof.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_feature_sunroofActionPerformed(evt);
            }
        });

        jCheckBox_feauture_heat.setText("Heated Seats");

        jCheckBox_blue.setText("BlueTooth");

        jCheckBox_electric.setText("Electric windows");

        jCheckBox_navigation.setText("Navigation System");

        jCheckBox_feature_gps.setText("GPS");

        jCheckBox_feauture_automatic.setText("Automatic Parking Assist");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jCheckBox_feature_sunroof, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCheckBox_feature_air_bags, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCheckBox_feature_air_cond, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCheckBox_feauture_heat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCheckBox_blue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCheckBox_electric, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox_navigation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCheckBox_feature_gps)
                    .addComponent(jCheckBox_feauture_automatic))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox_feature_air_cond)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jCheckBox_feauture_heat, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jCheckBox_navigation, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox_feature_air_bags)
                    .addComponent(jCheckBox_blue)
                    .addComponent(jCheckBox_feature_gps))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox_feature_sunroof)
                    .addComponent(jCheckBox_electric)
                    .addComponent(jCheckBox_feauture_automatic))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 400, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Features");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        jTextField_model.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextField_model.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jPanel3.add(jTextField_model, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 160, 40));

        jComboBox_brand.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jComboBox_brand.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jComboBox_brand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_brandActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBox_brand, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 180, 40));

        jComboBox_fuel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jComboBox_fuel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gas", "Diesel" }));
        jComboBox_fuel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jPanel3.add(jComboBox_fuel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 160, 40));

        jComboBox_color.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jComboBox_color.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "yellow", "red", "black", "blue", "yellow", "Green", "White" }));
        jComboBox_color.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jPanel3.add(jComboBox_color, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 210, 40));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Gearbox:");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, 80, -1));

        jSpinner_search_id.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jSpinner_search_id.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jPanel3.add(jSpinner_search_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 120, 150, -1));

        btn_add_car_image.setBackground(new java.awt.Color(255, 153, 51));
        btn_add_car_image.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_add_car_image.setForeground(new java.awt.Color(255, 255, 255));
        btn_add_car_image.setText("   Add car image");
        btn_add_car_image.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btn_add_car_image.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add_car_imageActionPerformed(evt);
            }
        });
        jPanel3.add(btn_add_car_image, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 550, 190, 40));

        jRadioButton_autmatic.setBackground(new java.awt.Color(0, 102, 102));
        buttonGroup1.add(jRadioButton_autmatic);
        jRadioButton_autmatic.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton_autmatic.setText("Automatic");
        jRadioButton_autmatic.setOpaque(true);
        jPanel3.add(jRadioButton_autmatic, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, -1, -1));

        jRadioButton_manual.setBackground(new java.awt.Color(0, 102, 102));
        buttonGroup1.add(jRadioButton_manual);
        jRadioButton_manual.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton_manual.setText("Manual");
        jRadioButton_manual.setOpaque(true);
        jPanel3.add(jRadioButton_manual, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, -1, -1));

        btn_brand_list1.setBackground(new java.awt.Color(255, 153, 51));
        btn_brand_list1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_brand_list1.setForeground(new java.awt.Color(255, 255, 255));
        btn_brand_list1.setText("Brand List");
        btn_brand_list1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btn_brand_list1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_brand_list1ActionPerformed(evt);
            }
        });
        jPanel3.add(btn_brand_list1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 490, 136, 40));

        jSpinner_price.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jSpinner_price.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jPanel3.add(jSpinner_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 282, 200, 40));

        jComboBox_classs.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jComboBox_classs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "OLD", "NEW", " " }));
        jComboBox_classs.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jPanel3.add(jComboBox_classs, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, 210, 40));

        btn_delete.setBackground(new java.awt.Color(255, 153, 51));
        btn_delete.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_delete.setForeground(new java.awt.Color(255, 255, 255));
        btn_delete.setText("Delete");
        btn_delete.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });
        jPanel3.add(btn_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 490, 120, 40));

        jButton2_update.setBackground(new java.awt.Color(255, 153, 51));
        jButton2_update.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2_update.setForeground(new java.awt.Color(255, 255, 255));
        jButton2_update.setText("Update");
        jButton2_update.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jButton2_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_updateActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 490, 130, 40));

        btn_car_list.setBackground(new java.awt.Color(255, 153, 51));
        btn_car_list.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_car_list.setForeground(new java.awt.Color(255, 255, 255));
        btn_car_list.setText("Car List");
        btn_car_list.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btn_car_list.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_car_listActionPerformed(evt);
            }
        });
        jPanel3.add(btn_car_list, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 550, 140, 40));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("id ");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 120, 30, 30));

        jSpinner_passenger1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jSpinner_passenger1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jPanel3.add(jSpinner_passenger1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 150, -1));

        jButton_search.setBackground(new java.awt.Color(0, 153, 255));
        jButton_search.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_search.setForeground(new java.awt.Color(255, 255, 255));
        jButton_search.setText("Search");
        jButton_search.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jButton_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_searchActionPerformed(evt);
            }
        });
        jPanel3.add(jButton_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 160, 110, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 903, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ResetActionPerformed
        jComboBox_brand.setSelectedIndex(0);
        jTextField_model.setText("");
        jComboBox_fuel.setSelectedIndex(0);
        jSpinner_passenger1.setValue(0);
        jComboBox_color.setSelectedIndex(0);
        jTextField_class.setText("");
        jSpinner_price.setValue(10);
        jRadioButton_autmatic.setSelected(false);
        jRadioButton_manual.setSelected(false);

        jCheckBox_feature_air_cond.setSelected(false);
        jCheckBox_feature_air_bags.setSelected(false);
        jCheckBox_feature_sunroof.setSelected(false);
        jCheckBox_feauture_heat.setSelected(false);
        jCheckBox_blue.setSelected(false);
        jCheckBox_electric.setSelected(false);
        jCheckBox_navigation.setSelected(false);
        jCheckBox_feature_gps.setSelected(false);
        jCheckBox_feauture_automatic.setSelected(false);

    }//GEN-LAST:event_btn_ResetActionPerformed

    private void jButton_add_carActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_add_carActionPerformed
        String brand = jComboBox_brand.getSelectedItem().toString();
        String model = jTextField_model.getText();
        String fuel = jComboBox_fuel.getSelectedItem().toString();
        int passenger = (int) jSpinner_passenger1.getValue();
        String color = jComboBox_color.getSelectedItem().toString();
        String classs = jComboBox_classs.getSelectedItem().toString();
        int price = (int) jSpinner_price.getValue();
        String Gearbox = "Automatic";
        String air_con = "no";
        String airbags = "no";
        String suroof = "no";
        String heats_seats = "no";
        String bluetooth = "no";
        String electric_window = "no";
        String nav_system = "no";
        String gps = "no";
        String Automatic_park = "no";

        if (jRadioButton_manual.isSelected()) {
            Gearbox = "Manual";
        }
        if (jCheckBox_feature_air_cond.isSelected()) {
            air_con = "yes";
        }
        if (jCheckBox_feature_air_bags.isSelected()) {
            airbags = "yes";
        }
        if (jCheckBox_feature_sunroof.isSelected()) {

            suroof = "yes";
        }
        if (jCheckBox_feauture_heat.isSelected()) {
            heats_seats = "yes";

        }
        if (jCheckBox_blue.isSelected()) {
            bluetooth = "yes";

        }
        if (jCheckBox_electric.isSelected()) {
            electric_window = "yes";

        }
        if (jCheckBox_navigation.isSelected()) {
            nav_system = "yes";

        }
        if (jCheckBox_feature_gps.isSelected()) {

            gps = "yes";
        }
        if (jCheckBox_feauture_automatic.isSelected()) {

            Automatic_park = "yes";
        }
         if(verify())
         {
        car.addCAR(brand, model, fuel, passenger, color, classs, price, Gearbox, air_con, airbags, suroof, heats_seats, bluetooth, electric_window, nav_system, gps, Automatic_park);
         }

    }//GEN-LAST:event_jButton_add_carActionPerformed

    private void jCheckBox_feature_sunroofActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_feature_sunroofActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_feature_sunroofActionPerformed

    private void btn_add_car_imageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add_car_imageActionPerformed
            car_image car1=new car_image();
           car1.setVisible(true);
    }//GEN-LAST:event_btn_add_car_imageActionPerformed

    private void btn_brand_list1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_brand_list1ActionPerformed
        all_brand_logo b1=new all_brand_logo();
        b1.setVisible(true);
    }//GEN-LAST:event_btn_brand_list1ActionPerformed

    private void jButton_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_searchActionPerformed
       int car_id=(int) jSpinner_search_id.getValue();
       Car car_new =car.getcarByid(car_id);
       if(car_new ==null)
       {
                      JOptionPane.showMessageDialog(this,"No car with This ID","invalid Information",2);
       }
       else
       {
           JOptionPane.showMessageDialog(this,"Now Car information","valid Information",1);
           jTextField_model.setText(car_new.getModel());
           jComboBox_brand.setSelectedItem(car_new.getBrand());
           jComboBox_fuel.setSelectedItem(car_new.getFuel());
           jSpinner_passenger1.setValue(car_new.getPassenger());
           jComboBox_color.setSelectedItem(car_new.getColor());
           jComboBox_classs.setSelectedItem(car_new.getClasss());
           jSpinner_price.setValue(car_new.getPrice());
           
           if(car_new.getGearbox().equals("manual"))
           {
               jRadioButton_manual.setSelected(true);
           }
           if(car_new.getAir_con().equals("yes"))
           {
              jCheckBox_feature_air_cond.setSelected(true);
           }
           if(car_new.getAirbags().equals("yes"))
           {
              jCheckBox_feature_air_bags.setSelected(true);
           }
            if(car_new.getSuroof().equals("yes"))
           {
              jCheckBox_feature_sunroof.setSelected(true);
           }
              if(car_new.getHeats_seats().equals("yes"))
           {
              jCheckBox_feauture_heat.setSelected(true);
           }
               if(car_new.getBluetooth().equals("yes"))
           {
              jCheckBox_blue.setSelected(true);
           }
                   if(car_new.getElectric_window().equals("yes"))
           {
                   jCheckBox_electric.setSelected(true);
           }
                if(car_new.getNav_system().equals("yes"))
           {
                   jCheckBox_navigation.setSelected(true);
           }
                   if(car_new.getGps().equals("yes"))
           {
                   jCheckBox_feature_gps.setSelected(true);
           } 
                    if(car_new.getAutomatic_park().equals("yes"))
           {
                  jCheckBox_feauture_automatic.setSelected(true);
           }       
  
       }
       
    }//GEN-LAST:event_jButton_searchActionPerformed

    private void jComboBox_brandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_brandActionPerformed
       
    }//GEN-LAST:event_jComboBox_brandActionPerformed

    private void jButton2_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_updateActionPerformed
        int id=(int) jSpinner_search_id.getValue();
        String brand = jComboBox_brand.getSelectedItem().toString();
        String model = jTextField_model.getText();
        String fuel = jComboBox_fuel.getSelectedItem().toString();
        int passenger = (int) jSpinner_passenger1.getValue();
        String color = jComboBox_color.getSelectedItem().toString();
        String classs = jComboBox_classs.getSelectedItem().toString();
           int price = (int) jSpinner_price.getValue();
        String Gearbox = "Automatic";
        String air_con = "no";
        String airbags = "no";
        String suroof = "no";
        String heats_seats = "no";
        String bluetooth = "no";
        String electric_window = "no";
        String nav_system = "no";
        String gps = "no";
        String Automatic_park = "no";

        if (jRadioButton_manual.isSelected()) {
            Gearbox = "Manual";
        }
        if (jCheckBox_feature_air_cond.isSelected()) {
            air_con = "yes";
        }
        if (jCheckBox_feature_air_bags.isSelected()) {
            airbags = "yes";
        }
        if (jCheckBox_feature_sunroof.isSelected()) {

            suroof = "yes";
        }
        if (jCheckBox_feauture_heat.isSelected()) {
            heats_seats = "yes";

        }
        if (jCheckBox_blue.isSelected()) {
            bluetooth = "yes";

        }
        if (jCheckBox_electric.isSelected()) {
            electric_window = "yes";

        }
        if (jCheckBox_navigation.isSelected()) {
            nav_system = "yes";

        }
        if (jCheckBox_feature_gps.isSelected()) {

            gps = "yes";
        }
        if (jCheckBox_feauture_automatic.isSelected()) {

            Automatic_park = "yes";
        }
         if(verify())
         {
             car.update_car(id, brand, model, fuel, passenger, color, classs, price, Gearbox, air_con, airbags, suroof, heats_seats, bluetooth, electric_window, nav_system, gps, Automatic_park);
         }
    }//GEN-LAST:event_jButton2_updateActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        int id=(int) jSpinner_search_id.getValue();
        int confirm=JOptionPane.showConfirmDialog(null, "Are you sure you want to delete new Car?", "confirm",JOptionPane.YES_NO_OPTION);
             if(confirm==JOptionPane.YES_NO_OPTION)
            {
               car.delete_car(id);
               JOptionPane.showMessageDialog(this, "delete successfully!.......");
            }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_car_listActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_car_listActionPerformed
        carList l2=new carList();
        l2.setVisible(true);
    }//GEN-LAST:event_btn_car_listActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Car_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Car_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Car_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Car_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Car_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Reset;
    private javax.swing.JButton btn_add_car_image;
    private javax.swing.JButton btn_brand_list1;
    private javax.swing.JButton btn_car_list;
    private javax.swing.JButton btn_delete;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JButton jButton2_update;
    private javax.swing.JButton jButton_add_car;
    private javax.swing.JButton jButton_search;
    private javax.swing.JCheckBox jCheckBoxGearbox_manual;
    private javax.swing.JCheckBox jCheckBox_Gearbox_auto;
    private javax.swing.JCheckBox jCheckBox_blue;
    private javax.swing.JCheckBox jCheckBox_electric;
    private javax.swing.JCheckBox jCheckBox_feature_air_bags;
    private javax.swing.JCheckBox jCheckBox_feature_air_cond;
    private javax.swing.JCheckBox jCheckBox_feature_gps;
    private javax.swing.JCheckBox jCheckBox_feature_sunroof;
    private javax.swing.JCheckBox jCheckBox_feauture_automatic;
    private javax.swing.JCheckBox jCheckBox_feauture_heat;
    private javax.swing.JCheckBox jCheckBox_navigation;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox_brand;
    private javax.swing.JComboBox<String> jComboBox_classs;
    private javax.swing.JComboBox<String> jComboBox_color;
    private javax.swing.JComboBox<String> jComboBox_fuel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton_autmatic;
    private javax.swing.JRadioButton jRadioButton_manual;
    private javax.swing.JSpinner jSpinner_passenger1;
    private javax.swing.JSpinner jSpinner_price;
    private javax.swing.JSpinner jSpinner_search_id;
    private javax.swing.JTextField jTextField_class;
    private javax.swing.JTextField jTextField_model;
    private javax.swing.JTextField jTextField_price;
    private javax.swing.JLabel product_logo;
    private javax.swing.JLabel product_logo1;
    // End of variables declaration//GEN-END:variables
}
