/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package car_rental_management_system;

import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class loading_screen extends javax.swing.JFrame {



    /**
     * Creates new form loading_screen
     */
    public loading_screen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        loadingbar = new javax.swing.JProgressBar();
        loadinglable = new javax.swing.JLabel();
        loadingvalue = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Car Rental Management Sytem");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 333, 42));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Car-Rental-Software.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 120, 291, 282));

        loadingbar.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        jPanel1.add(loadingbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 870, 20));

        loadinglable.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        loadinglable.setText("Loading...");
        jPanel1.add(loadinglable, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 426, 200, 30));

        loadingvalue.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        loadingvalue.setText("0%");
        jPanel1.add(loadingvalue, new org.netbeans.lib.awtextra.AbsoluteConstraints(816, 436, 40, 20));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car_rental_management_system/rental 445.jpg"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 460));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loading_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loading_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loading_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loading_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
          loading_screen l1=new loading_screen();
          Register_sign_up r1=new  Register_sign_up();
          l1.setVisible(true);
          try{
              for(int i=0;i<=100;i++)
              {
                 Thread.sleep(100);
                 l1.loadingvalue.setText(i+"%");
                 if(i==10)
                 {
                     l1.loadinglable.setText("Turning on Modules.....");
                 }
                 if(i==20)
                 {
                     l1.loadinglable.setText("Loading Modules..........");
                 }
                 if(i==50)
                 {
                     l1.loadinglable.setText("Connecting to DataBase...");
                 }
                 if(i==70)
                 {
                     l1.loadinglable.setText("Connection Successfully..");
                 }
                 if(i==80)
                 {
                     l1.loadinglable.setText("Launching Application......");
                 }
                 l1.loadingbar.setValue(i);
                  if(i==100)
             {
                 l1.setVisible(false);
                 r1.setVisible(true);
             }
          }
          }
          catch(Exception e){
              JOptionPane.showMessageDialog(null,e);
          }
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar loadingbar;
    private javax.swing.JLabel loadinglable;
    private javax.swing.JLabel loadingvalue;
    // End of variables declaration//GEN-END:variables
}
