/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package car_rental_management_system;
import java.awt.print.PrinterException;
import javax.swing.table.TableModel;
/**
 *
 * @author Administrator
 */
public class print extends javax.swing.JFrame {

    /**
     * Creates new form print
     */
    public print() {
        initComponents();
    }
    String ltotal;
    String pay;
    String lbal;
    String lcity;
    String lcustomer;
    public print(String TOTAL,String payment,String balnce,String city,String customer,TableModel table1) throws PrinterException {
        initComponents();
        
        this.ltotal=TOTAL;
        this.pay=payment;
        this.lbal=balnce;
        this.lcity=city;
        this.lcustomer=customer;
           for(int i=0;i<table1.getRowCount();i++)
         {
               String BRAND_MODEL=(String)table1.getValueAt(i, 0);
            String Price=(String)table1.getValueAt(i, 1);
             int  total=(int)table1.getValueAt(i, 3);
              String City=(String)table1.getValueAt(i, 4);
                String Customer=(String)table1.getValueAt(i, 5);
        jTextArea_print.setText(jTextArea_print.getText()+"*******************************************************************************\n");
        jTextArea_print.setText(jTextArea_print.getText()+"**************************CAR RENTAL MANAGEMENT SYSTEM ***********************\n");
        jTextArea_print.setText(jTextArea_print.getText()+"************************************PRINT RECEIPT**************************\n");
         jTextArea_print.setText(jTextArea_print.getText()+"Customer:"+Customer);
            jTextArea_print.setText(jTextArea_print.getText()+"\n"); 
        jTextArea_print.setText(jTextArea_print.getText()+"CITY:"+City);
        jTextArea_print.setText(jTextArea_print.getText()+"\n"); 
       jTextArea_print.setText(jTextArea_print.getText()+"BRAND MODEL :"+BRAND_MODEL+"\n"+"Price :"+Price+ "\n" +"total :"+total);
        }
         jTextArea_print.setText(jTextArea_print.getText()+"\n");
         jTextArea_print.setText(jTextArea_print.getText()+"\n");
           jTextArea_print.setText(jTextArea_print.getText()+"*******************************************************************************\n");
          jTextArea_print.setText(jTextArea_print.getText()+"           "+"TOTAL COST:"+TOTAL+               "\n"); 
           jTextArea_print.setText(jTextArea_print.getText()+"                 "+"PAY/per day:"+payment+               "\n"); 
            jTextArea_print.setText(jTextArea_print.getText()+"            "+"BALANCE:"+balnce+               "\n"); 
         jTextArea_print.setText(jTextArea_print.getText()+"*******************************************************************************\n");
        jTextArea_print.setText(jTextArea_print.getText()+"***********************Thank you came again************************************\n");
        jTextArea_print.print();

    }
 
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_print = new javax.swing.JTextArea();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(391, 430));

        jTextArea_print.setColumns(20);
        jTextArea_print.setRows(5);
        jTextArea_print.setPreferredSize(new java.awt.Dimension(422, 439));
        jScrollPane1.setViewportView(jTextArea_print);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new print().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea_print;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
