/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package car_rental_management_system;

import Classes.data_base;
import java.awt.Desktop;
import java.awt.Label;
import java.net.URL;
import java.sql.SQLException;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.sql.Statement;
import javax.swing.JOptionPane;


/**
 *
 * @author Administrator
 */
public class Register_sign_up extends javax.swing.JFrame {

    /**
     * Creates new form Register_sign_up
     */
    public Register_sign_up() {
        initComponents();
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jFrame3 = new javax.swing.JFrame();
        jColorChooser1 = new javax.swing.JColorChooser();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        m_password = new javax.swing.JLabel();
        scrollbar1 = new java.awt.Scrollbar();
        canvas1 = new java.awt.Canvas();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        scrollPane1 = new java.awt.ScrollPane();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        label6 = new java.awt.Label();
        label7 = new java.awt.Label();
        label8 = new java.awt.Label();
        label9 = new java.awt.Label();
        label10 = new java.awt.Label();
        label11 = new java.awt.Label();
        scrollbar2 = new java.awt.Scrollbar();
        jLabel11 = new java.awt.Label();
        m_lname = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        txtusername = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtfname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        txtcountry = new javax.swing.JComboBox<>();
        Country = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        checkbox = new javax.swing.JCheckBox();
        btn_register = new javax.swing.JButton();
        btnfacebook = new javax.swing.JButton();
        btninsta = new javax.swing.JButton();
        btntwitter = new javax.swing.JButton();
        m_fname = new javax.swing.JLabel();
        m_email = new javax.swing.JLabel();
        btn_cancel = new javax.swing.JButton();
        btn_goto_login = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        m_phone = new javax.swing.JLabel();
        txtphone = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jTextField1_country = new javax.swing.JTextField();
        txtUsername = new javax.swing.JComboBox<>();
        jTextField1_username = new javax.swing.JTextField();
        Address = new javax.swing.JLabel();
        jTextField_address = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtgender = new javax.swing.JComboBox<>();
        jTextField_gender = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame3Layout = new javax.swing.GroupLayout(jFrame3.getContentPane());
        jFrame3.getContentPane().setLayout(jFrame3Layout);
        jFrame3Layout.setHorizontalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame3Layout.setVerticalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-instagram-37.png"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-facebook-37.png"))); // NOI18N
        jLabel7.setText("jLabel7");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        m_password.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        m_password.setForeground(new java.awt.Color(255, 0, 0));

        label1.setText("label1");

        label2.setText("label2");

        label3.setText("label3");

        label4.setText("label4");

        label5.setText("label5");

        label6.setText("label6");

        label7.setText("label7");

        label8.setText("label8");

        label9.setText("label9");

        label10.setText("label10");

        label11.setText("label11");

        jLabel11.setText("label12");

        m_lname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        m_lname.setForeground(new java.awt.Color(255, 0, 0));

        jLabel13.setText("jLabel13");

        jLabel14.setText("jLabel14");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/images.png"))); // NOI18N

        jLabel15.setText("jLabel11");

        jLabel16.setText("jLabel16");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setText("X");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("                                    Register ");

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane5.setViewportView(jTextArea2);

        txtusername.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        txtusername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtusernameKeyReleased(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("                       welcome to the Recar");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 331, 27));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Lest's get your all set up,so you can begin to make your first order!");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 371, 25));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("FirstName");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 76, 24));

        txtfname.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        txtfname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtfnameKeyReleased(evt);
            }
        });
        jPanel2.add(txtfname, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 287, 34));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("User_name");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 76, 24));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Email*");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 76, 24));

        txtemail.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        txtemail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtemailKeyReleased(evt);
            }
        });
        jPanel2.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 287, 40));

        txtcountry.setMaximumRowCount(5);
        txtcountry.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Pakistan", "united States", "india", "China", "" }));
        txtcountry.setAutoscrolls(true);
        txtcountry.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        txtcountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcountryActionPerformed(evt);
            }
        });
        jPanel2.add(txtcountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 410, 287, 36));

        Country.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Country.setText("Country");
        jPanel2.add(Country, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, 78, 36));

        password.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        password.setText("Password");
        jPanel2.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 500, 86, 30));

        jPasswordField1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyReleased(evt);
            }
        });
        jPanel2.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 530, 291, 44));

        checkbox.setText("I want to receive ReCar's email");
        checkbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxActionPerformed(evt);
            }
        });
        jPanel2.add(checkbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 570, -1, 30));

        btn_register.setBackground(new java.awt.Color(0, 153, 255));
        btn_register.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_register.setForeground(new java.awt.Color(255, 255, 255));
        btn_register.setText("Register");
        btn_register.setEnabled(false);
        btn_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registerActionPerformed(evt);
            }
        });
        jPanel2.add(btn_register, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 630, 130, 51));

        btnfacebook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-facebook-37.png"))); // NOI18N
        btnfacebook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfacebookActionPerformed(evt);
            }
        });
        jPanel2.add(btnfacebook, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 590, 30, 30));

        btninsta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-instagram-37.png"))); // NOI18N
        btninsta.setBorder(null);
        btninsta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninstaActionPerformed(evt);
            }
        });
        jPanel2.add(btninsta, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 590, 30, 30));

        btntwitter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-twitter-37.png"))); // NOI18N
        btntwitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntwitterActionPerformed(evt);
            }
        });
        jPanel2.add(btntwitter, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 590, 30, 30));

        m_fname.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        m_fname.setForeground(new java.awt.Color(255, 0, 0));
        jPanel2.add(m_fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, 110, 40));

        m_email.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        m_email.setForeground(new java.awt.Color(255, 0, 0));
        jPanel2.add(m_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 280, 140, 40));

        btn_cancel.setBackground(new java.awt.Color(255, 0, 0));
        btn_cancel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_cancel.setForeground(new java.awt.Color(255, 255, 255));
        btn_cancel.setText("Cancel");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });
        jPanel2.add(btn_cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 630, 130, 50));

        btn_goto_login.setBackground(new java.awt.Color(51, 204, 255));
        btn_goto_login.setForeground(new java.awt.Color(255, 255, 255));
        btn_goto_login.setText("Click here to login");
        btn_goto_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_goto_loginActionPerformed(evt);
            }
        });
        jPanel2.add(btn_goto_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 600, 160, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Phone*");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 70, 20));

        m_phone.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        m_phone.setForeground(new java.awt.Color(255, 0, 0));
        jPanel2.add(m_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 300, 140, 40));

        txtphone.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        txtphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtphoneActionPerformed(evt);
            }
        });
        jPanel2.add(txtphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, 290, 40));
        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        jPanel2.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 204, 51));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Register");
        jLabel17.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(315, Short.MAX_VALUE)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(310, 310, 310))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 50));

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 842, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 850, 50));

        jTextField1_country.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel2.add(jTextField1_country, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 410, 180, 40));

        txtUsername.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtUsername.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Customer", "Admin", " " }));
        txtUsername.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        jPanel2.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 290, 40));

        jTextField1_username.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel2.add(jTextField1_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 210, 170, 40));

        Address.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Address.setText("Address");
        jPanel2.add(Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 440, 90, 30));

        jTextField_address.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel2.add(jTextField_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 470, 290, 40));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Gender");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 110, 90, 20));

        txtgender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gender", "Male", "Female" }));
        txtgender.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        txtgender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtgenderActionPerformed(evt);
            }
        });
        jPanel2.add(txtgender, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 140, 90, 40));

        jTextField_gender.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel2.add(jTextField_gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 140, 80, 40));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car_rental_management_system/31e5f4b3028de0cff28b1d12e93e167a (1).jpg"))); // NOI18N
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 850, 660));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcountryActionPerformed
      String country=txtcountry.getSelectedItem().toString();
      jTextField1_country.setText(country);
    }//GEN-LAST:event_txtcountryActionPerformed

    private void btninstaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninstaActionPerformed
         try{
            Desktop.getDesktop().browse(new URL("https://www.instagram.com/recargram/").toURI());
        }
        catch(Exception e){
        }
    }//GEN-LAST:event_btninstaActionPerformed

    private void btnfacebookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfacebookActionPerformed
        try{
            Desktop.getDesktop().browse(new URL("https://www.facebook.com/ReCarCanada/").toURI());
        }
        catch(Exception e){
        }
    }//GEN-LAST:event_btnfacebookActionPerformed

    private void btntwitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntwitterActionPerformed
          try{
            Desktop.getDesktop().browse(new URL("https://twitter.com/recarcanada?lang=en").toURI());
        }
        catch(Exception e){
        }  
    }//GEN-LAST:event_btntwitterActionPerformed

    private void checkboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxActionPerformed
        if(checkbox.isSelected())
        {
            btn_register.setEnabled(true);
        }else{
            btn_register.setEnabled(false);
        }
    }//GEN-LAST:event_checkboxActionPerformed

    private void txtfnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfnameKeyReleased
         String username_pattern="^[a-zA-Z0-9]([._-](?![._-])|[a-zA-Z0-9]){3,18}[a-zA-Z0-9]$";
                   Pattern pattern=Pattern.compile(username_pattern);
                   Matcher match=pattern.matcher(txtfname.getText());
                   if(!match.matches())
                   {
                       m_fname.setText("Naming is incorrect");
                   }else
                   {
                       m_fname.setText(null);
                   }
    }//GEN-LAST:event_txtfnameKeyReleased

    private void txtemailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtemailKeyReleased
        String email_pattern="^[a-zA-Z0-9_!#$%&'*+/=?`{|}~^.-]+@[a-zA-Z0-9.-]+$";
        Pattern pattern=Pattern.compile(email_pattern);
        Matcher match=pattern.matcher(txtemail.getText());
        if(!match.matches())
        {
            m_email.setText("Email is incorrect");
        }else{
            m_email.setText(null);
        }
    }//GEN-LAST:event_txtemailKeyReleased

    private void jPasswordField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyReleased
         String password_pattern="^[a-zA-Z0-9_!#$%&'*+/=?`{|}~^.-]+@[a-zA-Z0-9.-]+$";
        Pattern pattern=Pattern.compile(password_pattern);
        Matcher match=pattern.matcher(jPasswordField1.getText());
        if(!match.matches())
        {
           m_password.setText("password is incorrect");
        }else{
            m_password.setText(null);
        }
    }//GEN-LAST:event_jPasswordField1KeyReleased

    private void btn_goto_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_goto_loginActionPerformed
             new login_system().setVisible(true);
             new Register_sign_up().setVisible(false);
        
                
    }//GEN-LAST:event_btn_goto_loginActionPerformed

    private void txtusernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtusernameKeyReleased
        String username_pattern="^[a-zA-Z0-9]([._-](?![._-])|[a-zA-Z0-9]){3,18}[a-zA-Z0-9]$";
        Pattern pattern=Pattern.compile(username_pattern);
        Matcher match=pattern.matcher(txtusername.getText());
        if(!match.matches())
        {
            m_lname.setText("user is incorrect");
        }else
        {
            m_lname.setText(null);
        }
    }//GEN-LAST:event_txtusernameKeyReleased

    private void txtphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtphoneActionPerformed
        String phone_pattern="^[0-9]*$";
        Pattern pattern=Pattern.compile(phone_pattern);
        Matcher match=pattern.matcher(txtphone.getText());
        if(!match.matches())
        {
            m_phone.setText("phone is incorrect");
        }else
        {
            m_phone.setText(null);
        }
    }//GEN-LAST:event_txtphoneActionPerformed

    private void btn_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registerActionPerformed
        
        String  fname=txtfname.getText().toString();
        String  username=txtUsername.getSelectedItem().toString();
        String  email=txtemail.getText();
        String  phone=txtphone.getText();
        String  pass=jPasswordField1.getText();
        String address=jTextField_address.getText();
        String country=txtcountry.getSelectedItem().toString();
        String gender=txtgender.getSelectedItem().toString();
        int chk=0;
          if(fname.trim().equals(""))
        {
            JOptionPane.showMessageDialog(this, "please enter the full_name...");
            chk=1;
        }
        if(username.trim().equals(""))
        {
            JOptionPane.showMessageDialog(this, "please enter the username...");
            chk=1;
        }
         if(email.trim().equals(""))
        {
            JOptionPane.showMessageDialog(this, "please enter the email...");
            chk=1;
        }
          if(phone.trim().equals(""))
        {
            JOptionPane.showMessageDialog(this, "please enter the phone...");
            chk=1;
        }
          if(pass.trim().equals(""))
        {
            JOptionPane.showMessageDialog(this, "please enter the password...");
            chk=1;
        }
          if(country.equals(""))
        {
            JOptionPane.showMessageDialog(this, "please enter the country...");
            chk=1;
        }
           if(address.equals(""))
        {
            JOptionPane.showMessageDialog(this, "please enter the address...");
            chk=1;
        }
             if(gender.equals(""))
        {
            JOptionPane.showMessageDialog(this, "please enter the gender...");
            chk=1;
        }
         int confirm=JOptionPane.showConfirmDialog(null, "Are you sure you want to  Register?", "confirm",JOptionPane.YES_NO_OPTION);
        if(chk==0&&confirm==JOptionPane.YES_NO_OPTION)
        {
          JOptionPane.showMessageDialog(this, "Register Form is Successfully ");
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Register Form is failed.. please try again ");
        }
       
        try{
            Statement s=data_base.getconect().createStatement();
            s.executeUpdate("INSERT INTO user(first_name, username, email, phone, password,country,address,gender)"
                    + " VALUES ('"+fname+"','"+username+"','"+email+"','"+phone+"','"+pass+"','"+country+"','"+address+"','"+gender+"')");
            this.setVisible(false);
            new login_system().setVisible(true);
             JOptionPane.showMessageDialog(this,"Your Account wiil be create. LOGIN NOW");
        }catch(SQLException e){
            System.out.println(e);
            
        }
        txtfname.setText("");
        jTextField1_username.setText("");
        txtusername.setText("");
       txtemail.setText("");
        txtphone.setText("");
        jPasswordField1.setText("");
        jTextField1_country.setText("");
        jTextField_gender.setText("");
        jTextField_address.setText("");
         
    }//GEN-LAST:event_btn_registerActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        String username=txtUsername.getSelectedItem().toString();
        jTextField1_username.setText(username);
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
       System.exit(0);
    }//GEN-LAST:event_btn_cancelActionPerformed

    private void txtgenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgenderActionPerformed
String address=txtgender.getSelectedItem().toString();
      jTextField_gender.setText(address);      
        
    }//GEN-LAST:event_txtgenderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register_sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register_sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register_sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register_sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register_sign_up().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Address;
    private javax.swing.JLabel Country;
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_goto_login;
    private javax.swing.JButton btn_register;
    private javax.swing.JButton btnfacebook;
    private javax.swing.JButton btninsta;
    private javax.swing.JButton btntwitter;
    private java.awt.Canvas canvas1;
    private javax.swing.JCheckBox checkbox;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JFrame jFrame3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private java.awt.Label jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField1_country;
    private javax.swing.JTextField jTextField1_username;
    private javax.swing.JTextField jTextField_address;
    private javax.swing.JTextField jTextField_gender;
    private java.awt.Label label1;
    private java.awt.Label label10;
    private java.awt.Label label11;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.Label label9;
    private javax.swing.JLabel m_email;
    private javax.swing.JLabel m_fname;
    private javax.swing.JLabel m_lname;
    private javax.swing.JLabel m_password;
    private javax.swing.JLabel m_phone;
    private javax.swing.JLabel password;
    private java.awt.ScrollPane scrollPane1;
    private java.awt.Scrollbar scrollbar1;
    private java.awt.Scrollbar scrollbar2;
    private javax.swing.JComboBox<String> txtUsername;
    private javax.swing.JComboBox<String> txtcountry;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtfname;
    private javax.swing.JComboBox<String> txtgender;
    private javax.swing.JTextField txtphone;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
